### ISSUE TITLE
Clear water

### ISSUE THREAD

**Issue by shahabisnotavailable** [I-No-oNe/View-Model#3]
when i have the mod installed, water becomes FULLY clear.
![2024-10-04_18 29 09](https://github.com/user-attachments/assets/9b9e3483-4dae-4627-b0db-fdb91db7c1ea)

**Comment by shahabisnotavailable** [comment]
only when i turn off the mod does my water go back to normal

**Comment by I-No-oNe** [comment]
There is a problem when u swim in water ur hands will move down, in order to fix that I canceled the water overlay for the camera

**Comment by I-No-oNe** [comment]
There is a problem when u enter water ur hands will move down, in order to fix that I canceled the water overlay for the camera
(So this isn't a bug -> it's a feature)

**Comment by shahabisnotavailable** [comment]
> There is a problem when u enter water ur hands will move down, in order to fix that I canceled the water overlay for the camera (So this isn't a bug -> it's a feature)

i see, there is another view model mod that does more or less the same except it doesnt have the static hand animations as yours (thats why i prefered yours) it just felt a lil cheaty to use this mod but thx for clarifying.

**Comment by I-No-oNe** [comment]
I can remove it if u want

**Comment by I-No-oNe** [comment]
Or add a way to disable it

**Comment by shahabisnotavailable** [comment]
> Or add a way to disable it

i think it is better to atleast add a way to disable it, this mod has more customisabilty compared to others ive seen its just having clear water defeats the purpose of having a "legit world" if you know what i mean.

**Comment by I-No-oNe** [comment]
K
